
obj-$(CONFIG_CHARGER_CP_PPS)	+= pd_policy_manager.o
obj-$(CONFIG_UPM6720_CP) += upm6720_charger.o
# A06_V code for SR-AL7160V-01-135|SR-AL7160V-01-136 by xiongxiaoliang at 20240902 start
obj-$(CONFIG_NU2115A_CP) += nu2115a.o
obj-$(CONFIG_SGM41606S_CP) += sgm41606S_charger.o
obj-$(CONFIG_NX853X_CP) += nx853x_charger.o
# A06_V code for SR-AL7160V-01-135|SR-AL7160V-01-136 by xiongxiaoliang at 20240902 end
