obj-$(CONFIG_SILEAD_FP)                += silead/
obj-$(CONFIG_FINGERPRINT_FOCALTECH)    += focaltech/
obj-$(CONFIG_CDFINGER_FP)              += cdfinger/
obj-$(CONFIG_MTK_FINGERPRINT_O22_SUPPORT)               += fingerprint_sysfs.o

