ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/input/touchscreen/O22/touch_common/

obj-$(CONFIG_TOUCHSCREEN_JADARD_CHIPSET_O22) += jadard_ic_JD9522T_o22.o
jadard_ic_JD9522T_o22-objs += jadard_debug.o
jadard_ic_JD9522T_o22-objs += jadard_sorting.o
jadard_ic_JD9522T_o22-objs += jadard_ic_JD9522T.o
jadard_ic_JD9522T_o22-objs += jadard_module.o
jadard_ic_JD9522T_o22-objs += jadard_common.o
jadard_ic_JD9522T_o22-objs += jadard_platform.o
