/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 MediaTek Inc.
 */

#ifndef __LINUX_POWER_SUPPLY_EXT_H__
#define __LINUX_POWER_SUPPLY_EXT_H__

#include <linux/device.h>
#include <linux/workqueue.h>
#include <linux/leds.h>
#include <linux/spinlock.h>
#include <linux/notifier.h>
#include <linux/android_kabi.h>
#include <linux/power_supply.h>

enum {
	POWER_SUPPLY_HEALTH_UNDERVOLTAGE = POWER_SUPPLY_HEALTH_HOT + 1,
	POWER_SUPPLY_HEALTH_OVERHEATLIMIT,
	POWER_SUPPLY_HEALTH_MAX,
};

enum {
	POWER_SUPPLY_DP_DM_UNKNOWN = 0,
	POWER_SUPPLY_DP_DM_PREPARE = 1,
	POWER_SUPPLY_DP_DM_UNPREPARE = 2,
	POWER_SUPPLY_DP_DM_CONFIRMED_HVDCP3 = 3,
	POWER_SUPPLY_DP_DM_DP_PULSE = 4,
	POWER_SUPPLY_DP_DM_DM_PULSE = 5,
	POWER_SUPPLY_DP_DM_DP0P6_DMF = 6,
	POWER_SUPPLY_DP_DM_DP0P6_DM3P3 = 7,
	POWER_SUPPLY_DP_DM_DPF_DMF = 8,
	POWER_SUPPLY_DP_DM_DPR_DMR = 9,
	POWER_SUPPLY_DP_DM_HVDCP3_SUPPORTED = 10,
	POWER_SUPPLY_DP_DM_ICL_DOWN = 11,
	POWER_SUPPLY_DP_DM_ICL_UP = 12,
	POWER_SUPPLY_DP_DM_FORCE_5V = 13,
	POWER_SUPPLY_DP_DM_FORCE_9V = 14,
	POWER_SUPPLY_DP_DM_FORCE_12V = 15,
	POWER_SUPPLY_DP_DM_CONFIRMED_HVDCP3P5 = 16,
};

enum {
	POWER_SUPPLY_PL_NONE,
	POWER_SUPPLY_PL_USBIN_USBIN,
	POWER_SUPPLY_PL_USBIN_USBIN_EXT,
	POWER_SUPPLY_PL_USBMID_USBMID,
};

enum {
	POWER_SUPPLY_CHARGER_SEC_NONE = 0,
	POWER_SUPPLY_CHARGER_SEC_CP,
	POWER_SUPPLY_CHARGER_SEC_PL,
	POWER_SUPPLY_CHARGER_SEC_CP_PL,
};

enum {
	POWER_SUPPLY_CP_NONE = 0,
	POWER_SUPPLY_CP_HVDCP3,
	POWER_SUPPLY_CP_HVDCP3P5,
	POWER_SUPPLY_CP_PPS,
	POWER_SUPPLY_CP_WIRELESS,
};

enum {
	POWER_SUPPLY_CONNECTOR_TYPEC,
	POWER_SUPPLY_CONNECTOR_MICRO_USB,
};

enum {
	POWER_SUPPLY_PL_STACKED_BATFET,
	POWER_SUPPLY_PL_NON_STACKED_BATFET,
};

/* Parallel output connection topology */
enum {
	POWER_SUPPLY_PL_OUTPUT_NONE,
	POWER_SUPPLY_PL_OUTPUT_VPH,
	POWER_SUPPLY_PL_OUTPUT_VBAT,
};

enum {
	POWER_SUPPLY_PD_INACTIVE = 0,
	POWER_SUPPLY_PD_ACTIVE,
	POWER_SUPPLY_PD_PPS_ACTIVE,
};

enum {
	POWER_SUPPLY_QC_CTM_DISABLE = BIT(0),
	POWER_SUPPLY_QC_THERMAL_BALANCE_DISABLE = BIT(1),
	POWER_SUPPLY_QC_INOV_THERMAL_DISABLE = BIT(2),
};

enum {
	POWER_SUPPLY_ALIGN_CHECKING = 0,
	POWER_SUPPLY_ALIGN_MOVE,
	POWER_SUPPLY_ALIGN_CENTERED,
	POWER_SUPPLY_ALIGN_ERROR,
};
enum power_supply_ext_property {
	POWER_SUPPLY_EXT_PROP_MIN = 1000,
	POWER_SUPPLY_EXT_PROP_CHARGE_COUNTER_SHADOW,
	POWER_SUPPLY_EXT_PROP_CHARGE_OTG_CONTROL,
	POWER_SUPPLY_EXT_PROP_CHARGE_POWERED_OTG_CONTROL,
	POWER_SUPPLY_EXT_PROP_CHARGE_TEMP,
	POWER_SUPPLY_EXT_PROP_CHARGE_UNO_CONTROL,
	POWER_SUPPLY_EXT_PROP_INPUT_CURRENT_MAX,
	POWER_SUPPLY_EXT_PROP_USBPD_RESET,
	POWER_SUPPLY_EXT_PROP_FILTER_CFG,
	POWER_SUPPLY_EXT_PROP_USB_HC,
	POWER_SUPPLY_EXT_PROP_USB_OTG,
	POWER_SUPPLY_EXT_PROP_CHARGE_ENABLED,
	POWER_SUPPLY_EXT_PROP_CHARGING_ENABLED,
	POWER_SUPPLY_EXT_PROP_INPUT_VOLTAGE_REGULATION,
	POWER_SUPPLY_EXT_PROP_BATT_FULL_CURRENT,
	POWER_SUPPLY_EXT_PROP_SOH,
	POWER_SUPPLY_EXT_PROP_FACTORY_MODE,
	POWER_SUPPLY_EXT_PROP_PD_SUPPORT,
	POWER_SUPPLY_EXT_PROP_AFC_CHARGER_MODE,
	POWER_SUPPLY_EXT_PROP_VCHGIN,
	POWER_SUPPLY_EXT_PROP_VWCIN,
	POWER_SUPPLY_EXT_PROP_VBYP,
	POWER_SUPPLY_EXT_PROP_VSYS,
	POWER_SUPPLY_EXT_PROP_VBAT,
	POWER_SUPPLY_EXT_PROP_VGPADC,
	POWER_SUPPLY_EXT_PROP_VCC1,
	POWER_SUPPLY_EXT_PROP_VCC2,
	POWER_SUPPLY_EXT_PROP_ICHGIN,
	POWER_SUPPLY_EXT_PROP_IWCIN,
	POWER_SUPPLY_EXT_PROP_IOTG,
	POWER_SUPPLY_EXT_PROP_ITX,
	POWER_SUPPLY_EXT_PROP_CO_ENABLE,
	POWER_SUPPLY_EXT_PROP_RR_ENABLE,
	POWER_SUPPLY_EXT_PROP_PM_FACTORY,
	POWER_SUPPLY_EXT_PROP_TDIE,
	POWER_SUPPLY_EXT_PROP_FAST_IAVG,
	POWER_SUPPLY_EXT_PROP_CURRENT_FULL,
	POWER_SUPPLY_EXT_PROP_USBPD_TEST_READ,

	/* from battery/sec_battery_common.h */
	POWER_SUPPLY_EXT_PROP_CHECK_SLAVE_I2C,
	POWER_SUPPLY_EXT_PROP_MULTI_CHARGER_MODE,
	POWER_SUPPLY_EXT_PROP_WIRELESS_OP_FREQ,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TRX_CMD,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TRX_VAL,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TX_ID,
	POWER_SUPPLY_EXT_PROP_WIRELESS_ERR,
	POWER_SUPPLY_EXT_PROP_WIRELESS_SWITCH,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TX_ENABLE,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TX_VOUT,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TX_IOUT,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TX_UNO_VIN,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TX_UNO_IIN,
	POWER_SUPPLY_EXT_PROP_WIRELESS_RX_CONNECTED,
	POWER_SUPPLY_EXT_PROP_WIRELESS_DUO_RX_POWER,
	POWER_SUPPLY_EXT_PROP_WIRELESS_AUTH_ADT_STATUS,
	POWER_SUPPLY_EXT_PROP_WIRELESS_AUTH_ADT_DATA,
	POWER_SUPPLY_EXT_PROP_WIRELESS_AUTH_ADT_SIZE,
	POWER_SUPPLY_EXT_PROP_WIRELESS_RX_TYPE,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TX_ERR,
	POWER_SUPPLY_EXT_PROP_WIRELESS_MIN_DUTY,
	POWER_SUPPLY_EXT_PROP_WIRELESS_SEND_FSK,
	POWER_SUPPLY_EXT_PROP_WIRELESS_RX_VOUT,
	POWER_SUPPLY_EXT_PROP_AICL_CURRENT,
	POWER_SUPPLY_EXT_PROP_CHECK_MULTI_CHARGE,
	POWER_SUPPLY_EXT_PROP_CHIP_ID,
	POWER_SUPPLY_EXT_PROP_ERROR_CAUSE,
	POWER_SUPPLY_EXT_PROP_SYSOVLO,
	POWER_SUPPLY_EXT_PROP_VBAT_OVP,
	POWER_SUPPLY_EXT_PROP_INBAT_VOLTAGE_FGSRC_SWITCHING,
	POWER_SUPPLY_EXT_PROP_USB_CONFIGURE,
	POWER_SUPPLY_EXT_PROP_WDT_STATUS,
	POWER_SUPPLY_EXT_PROP_HV_DISABLE,
	POWER_SUPPLY_EXT_PROP_FUELGAUGE_RESET,
	POWER_SUPPLY_EXT_PROP_FACTORY_VOLTAGE_REGULATION,
	POWER_SUPPLY_EXT_PROP_ANDIG_IVR_SWITCH,
	POWER_SUPPLY_EXT_PROP_FUELGAUGE_FACTORY,
	POWER_SUPPLY_EXT_PROP_DISABLE_FACTORY_MODE,
	POWER_SUPPLY_EXT_PROP_SUB_PBA_TEMP_REC,
	POWER_SUPPLY_EXT_PROP_CHARGE_POWER,
	POWER_SUPPLY_EXT_PROP_MEASURE_SYS,
	POWER_SUPPLY_EXT_PROP_MEASURE_INPUT,
	POWER_SUPPLY_EXT_PROP_WC_CONTROL,
	POWER_SUPPLY_EXT_PROP_CHGINSEL,
	POWER_SUPPLY_EXT_PROP_MONITOR_WORK,
	POWER_SUPPLY_EXT_PROP_JIG_GPIO,
	POWER_SUPPLY_EXT_PROP_SHIPMODE_TEST,
	POWER_SUPPLY_EXT_PROP_AUTO_SHIPMODE_CONTROL,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TIMER_ON,
	POWER_SUPPLY_EXT_PROP_CALL_EVENT,
	POWER_SUPPLY_EXT_PROP_WATER_DETECT,
	POWER_SUPPLY_EXT_PROP_SURGE,
	POWER_SUPPLY_EXT_PROP_OVERHEAT_NOTIFY,
	POWER_SUPPLY_EXT_PROP_OVERHEAT_HICCUP,
	POWER_SUPPLY_EXT_PROP_CHGIN_OK,
	POWER_SUPPLY_EXT_PROP_SUPLLEMENT_MODE,
	POWER_SUPPLY_EXT_PROP_RECHG_ON,
	POWER_SUPPLY_EXT_PROP_EOC_ON,
	POWER_SUPPLY_EXT_PROP_DISCHG_MODE,
	POWER_SUPPLY_EXT_PROP_CHG_MODE,
	POWER_SUPPLY_EXT_PROP_CHG_VOLTAGE,
	POWER_SUPPLY_EXT_PROP_BAT_VOLTAGE,
	POWER_SUPPLY_EXT_PROP_CHG_CURRENT,
	POWER_SUPPLY_EXT_PROP_DISCHG_CURRENT,
	POWER_SUPPLY_EXT_PROP_FASTCHG_LIMIT_CURRENT,
	POWER_SUPPLY_EXT_PROP_TRICKLECHG_LIMIT_CURRENT,
	POWER_SUPPLY_EXT_PROP_DISCHG_LIMIT_CURRENT,
	POWER_SUPPLY_EXT_PROP_RECHG_VOLTAGE,
	POWER_SUPPLY_EXT_PROP_EOC_VOLTAGE,
	POWER_SUPPLY_EXT_PROP_EOC_CURRENT,
	POWER_SUPPLY_EXT_PROP_POWERMETER_ENABLE,
	POWER_SUPPLY_EXT_PROP_TSD_ENABLE,
	POWER_SUPPLY_EXT_PROP_DUAL_BAT_DET,
	POWER_SUPPLY_EXT_PROP_CURRENT_EVENT,
	POWER_SUPPLY_EXT_PROP_MAX_DUTY_EVENT,
	POWER_SUPPLY_EXT_PROP_CHARGE_PORT,
	POWER_SUPPLY_EXT_PROP_WIRELESS_TX_AVG_CURR,
	POWER_SUPPLY_EXT_PROP_CURRENT_MEASURE,
	POWER_SUPPLY_EXT_PROP_DIRECT_CHARGER_MODE,
	POWER_SUPPLY_EXT_PROP_CHARGING_ENABLED_DC,
	POWER_SUPPLY_EXT_PROP_DIRECT_DONE,
	POWER_SUPPLY_EXT_PROP_DIRECT_FIXED_PDO,
	POWER_SUPPLY_EXT_PROP_DIRECT_WDT_CONTROL,
	POWER_SUPPLY_EXT_PROP_DIRECT_VOLTAGE_MAX,
	POWER_SUPPLY_EXT_PROP_DIRECT_CURRENT_MAX,
	POWER_SUPPLY_EXT_PROP_DIRECT_FLOAT_MAX,
	POWER_SUPPLY_EXT_PROP_DIRECT_ADC_CTRL,
	POWER_SUPPLY_EXT_PROP_DIRECT_HV_PDO,
	POWER_SUPPLY_EXT_PROP_DIRECT_PPS,
	POWER_SUPPLY_EXT_PROP_DIRECT_PPS_FAILED,
	POWER_SUPPLY_EXT_PROP_DIRECT_PPS_READY,
	POWER_SUPPLY_EXT_PROP_DIRECT_DETACHED,
	POWER_SUPPLY_EXT_PROP_DIRECT_BUCK_OFF,
	POWER_SUPPLY_EXT_PROP_DIRECT_HARD_RESET,
	POWER_SUPPLY_EXT_PROP_UPDATE_BATTERY_DATA,
	POWER_SUPPLY_EXT_PROP_WD_QBATTOFF,
	POWER_SUPPLY_EXT_PROP_WPC_DET_STATUS,
	POWER_SUPPLY_EXT_PROP_CHARGE_BOOST,
	POWER_SUPPLY_EXT_PROP_CHARGE_MODE,
	POWER_SUPPLY_EXT_PROP_FLED_BOOST_ON,
	POWER_SUPPLY_EXT_PROP_FLED_BOOST_OFF,
	POWER_SUPPLY_EXT_PROP_FGSRC_SWITCHING,
	POWER_SUPPLY_EXT_PROP_MAX,
};

enum power_supply_ext_type {
	POWER_SUPPLY_EXT_TYPE_MIN = 200,
	POWER_SUPPLY_EXT_TYPE_USB_HVDCP,		/* High Voltage DCP */
	POWER_SUPPLY_EXT_TYPE_USB_HVDCP_3,		/* Efficient High Voltage DCP */
	POWER_SUPPLY_EXT_TYPE_USB_HVDCP_3P5,	/* Efficient High Voltage DCP */
	POWER_SUPPLY_EXT_TYPE_USB_FLOAT,		/* Floating charger */
	POWER_SUPPLY_EXT_TYPE_BMS,			/* Battery Monitor System */
	POWER_SUPPLY_EXT_TYPE_PARALLEL,		/* Parallel Path */
	POWER_SUPPLY_EXT_TYPE_MAIN,			/* Main Path */
	POWER_SUPPLY_EXT_TYPE_UFP,			/* Type-C UFP */
	POWER_SUPPLY_EXT_TYPE_DFP,			/* Type-C DFP */
	POWER_SUPPLY_EXT_TYPE_CHARGE_PUMP,		/* Charge Pump */
	/* Added by Customer */
	POWER_SUPPLY_EXT_TYPE_MISC,
	POWER_SUPPLY_EXT_TYPE_HV_WIRELESS,
	POWER_SUPPLY_EXT_TYPE_PMA_WIRELESS,
	POWER_SUPPLY_EXT_TYPE_CARDOCK,
	POWER_SUPPLY_EXT_TYPE_UARTOFF,
	POWER_SUPPLY_EXT_TYPE_OTG,
	POWER_SUPPLY_EXT_TYPE_LAN_HUB,
	POWER_SUPPLY_EXT_TYPE_MHL_500,
	POWER_SUPPLY_EXT_TYPE_MHL_900,
	POWER_SUPPLY_EXT_TYPE_MHL_1500,
	POWER_SUPPLY_EXT_TYPE_MHL_USB,
	POWER_SUPPLY_EXT_TYPE_SMART_OTG,
	POWER_SUPPLY_EXT_TYPE_SMART_NOTG,
	POWER_SUPPLY_EXT_TYPE_POWER_SHARING,
	POWER_SUPPLY_EXT_TYPE_HV_MAINS,
	POWER_SUPPLY_EXT_TYPE_HV_MAINS_12V,
	POWER_SUPPLY_EXT_TYPE_HV_PREPARE_MAINS,
	POWER_SUPPLY_EXT_TYPE_HV_ERR,
	POWER_SUPPLY_EXT_TYPE_MHL_USB_100,
	POWER_SUPPLY_EXT_TYPE_MHL_2000,
	POWER_SUPPLY_EXT_TYPE_HV_UNKNOWN,
	POWER_SUPPLY_EXT_TYPE_MDOCK_TA,
	POWER_SUPPLY_EXT_TYPE_HMT_CONNECTED,
	POWER_SUPPLY_EXT_TYPE_HMT_CHARGE,
	POWER_SUPPLY_EXT_TYPE_WIRELESS_PACK,
	POWER_SUPPLY_EXT_TYPE_WIRELESS_PACK_TA,
	POWER_SUPPLY_EXT_TYPE_WIRELESS_STAND,
	POWER_SUPPLY_EXT_TYPE_WIRELESS_HV_STAND,
	POWER_SUPPLY_EXT_TYPE_PDIC,
	POWER_SUPPLY_EXT_TYPE_HV_MAINS_CHG_LIMIT,
	POWER_SUPPLY_EXT_TYPE_HV_QC20,
	POWER_SUPPLY_EXT_TYPE_HV_QC30,
	POWER_SUPPLY_EXT_TYPE_POGO,
	POWER_SUPPLY_EXT_TYPE_MAX,
};

/* Indicates USB Type-C CC connection status */
enum power_supply_typec_mode {
	POWER_SUPPLY_TYPEC_NONE,

	/* Acting as source */
	POWER_SUPPLY_TYPEC_SINK,		/* Rd only */
	POWER_SUPPLY_TYPEC_SINK_POWERED_CABLE,	/* Rd/Ra */
	POWER_SUPPLY_TYPEC_SINK_DEBUG_ACCESSORY,/* Rd/Rd */
	POWER_SUPPLY_TYPEC_SINK_AUDIO_ADAPTER,	/* Ra/Ra */
	POWER_SUPPLY_TYPEC_POWERED_CABLE_ONLY,	/* Ra only */

	/* Acting as sink */
	POWER_SUPPLY_TYPEC_SOURCE_DEFAULT,	/* Rp default */
	POWER_SUPPLY_TYPEC_SOURCE_MEDIUM,	/* Rp 1.5A */
	POWER_SUPPLY_TYPEC_SOURCE_HIGH,		/* Rp 3A */
	POWER_SUPPLY_TYPEC_DAM_DEFAULT,		/* Rp-1.5A/Rp-3A */
	POWER_SUPPLY_TYPEC_DAM_MEDIUM,		/* Rp-Default/Rp-1.5A */
	POWER_SUPPLY_TYPEC_DAM_HIGH,		/* Rp-Default/Rp-3A */

	/* Non Compliant */
	POWER_SUPPLY_TYPEC_NON_COMPLIANT,
	POWER_SUPPLY_TYPEC_RP_STD_STD,		/* Rp-Default/Rp-Default */
	POWER_SUPPLY_TYPEC_RP_MED_MED,		/* Rp-1.5A/Rp-1.5A */
	POWER_SUPPLY_TYPEC_RP_HIGH_HIGH,	/* Rp-3A/Rp-3A */
};

enum power_supply_typec_src_rp {
	POWER_SUPPLY_TYPEC_SRC_RP_STD,
	POWER_SUPPLY_TYPEC_SRC_RP_1P5A,
	POWER_SUPPLY_TYPEC_SRC_RP_3A
};

enum power_supply_typec_power_role {
	POWER_SUPPLY_TYPEC_PR_NONE,		/* CC lines in high-Z */
	POWER_SUPPLY_TYPEC_PR_DUAL,
	POWER_SUPPLY_TYPEC_PR_SINK,
	POWER_SUPPLY_TYPEC_PR_SOURCE,
};
#endif /* __LINUX_POWER_SUPPLY_H__ */
