# SPDX-License-Identifier: GPL-2.0
#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y				+= mediatek/
# A06_V code added for SR-AL5625-01-302 by zhengchao at 20240826 start
obj-y				+= huaqin/
# A06_V code added for SR-AL5625-01-302 by zhengchao at 20240826 end

obj-y				+= drb/
