# A06_V code for AL7160AV-521 by yuli at 20250421 start
ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/
# A06_V code for AL7160AV-521 by yuli at 20250421 end
obj-$(CONFIG_JIIOV_FP)    +=  jiiov_fingerprint.o

jiiov_fingerprint-objs := jiiov_platform.o jiiov_netlink.o custom.o

