#
# Makefile for usb typec manager drivers
#

obj-$(CONFIG_USB_TYPEC_MANAGER_NOTIFIER)     += mod-usb-typec-manager-notifier.o
mod-usb-typec-manager-notifier-$(CONFIG_USB_TYPEC_MANAGER_NOTIFIER)     := usb_typec_manager_notifier.o