#
# Makefile for the fingerprint drivers.
#
# A14_V code for AL6528AV-456 by yuli at 20250421 start
ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/
# A14_V code for AL6528AV-456 by yuli at 20250421 end
obj-$(CONFIG_CDFINGER_FP) += cdfingerfp.o

