obj-$(CONFIG_SILEAD_FP)                += silead/
obj-$(CONFIG_JIIOV_FP)                += jiiov/
obj-$(CONFIG_FINGERPRINT_FOCALTECH)    += focaltech/
obj-$(CONFIG_MTK_FINGERPRINT_O8_SUPPORT)               += fingerprint_sysfs.o

